### ISSUE TITLE
Interactive Addition - Skipped Lines (Ctrl-C) and Overescaping

### ISSUE THREAD

**Issue by progmem** [cronitorio/cronitor-cli#2]
In a server I have Cronitor installed on, I have the following `@reboot` line, which I'm skipping any time we need to add tasks with `cronitor discover`, since we already have other monitoring solutions in place (and I didn't think Cronitor supported `@reboot`):

`@reboot /bin/bash -l -c 'cd /path/to/application && ./reboot_task.sh'`

This is deemed a "complex" line by CronitorCLI, and given the following flow...

* Run `cronitor discover`
* Skip the `@reboot` line
* Add, update, or otherwise hit Enter/Return on any other line
* Cronitor updates the crontab and submits changes

...I end up with the following below over multiple runs: 

```
@reboot "/bin/bash -l -c 'cd /path/to/application && ./reboot_task.sh'"
@reboot "\"/bin/bash -l -c 'cd /path/to/application && ./reboot_task.sh'\""
@reboot "\"\\"/bin/bash -l -c 'cd /path/to/application && ./reboot_task.sh'\\"\""
```

Due to escaped characters getting re-escaped over multiple runs, I ultimately end up with tasks outside of Cronitor's monitoring that no longer perform what they need to.

As a note, I am not a Go developer by trade, but I did try hacking on it a little bit, and came up with [a possible solution that appears to work when I build and run](https://github.com/cronitorio/cronitor-cli/compare/master...progmem:line-modification-restraint), by only modifying lines that are receiving a monitor code for the first time.

**Comment by shaneharter** [comment]
@progmem Thank you for reporting the issue and providing a possible patch. I'll let you know what we find.

**Comment by shaneharter** [comment]
Somehow this issue was not closed when the patch was accepted. Thanks again!
