### ISSUE TITLE
Non-interative `cronitor discover`?

### ISSUE THREAD

**Issue by jmanuel1** [cronitorio/cronitor-cli#24]
Is there a way to run `cronitor discover` interactively and tell it to look only at my user-specific crontab? I'm trying to automate cronitor setup with ansible.

**Comment by shaneharter** [comment]
Yes, there is a --auto flag. You can also specify a crontab file or pipe one in to stdin. Run `cronitor help discover` for more details

**Comment by jmanuel1** [comment]
I'll try that. Thanks.

**Comment by jmanuel1** [comment]
I didn't get piping a file in to work, but specifying a file as an argument did.
