### ISSUE TITLE
are there pinned version cronitor download links?

### ISSUE THREAD

**Issue by zhammer** [cronitorio/cronitor-cli#5]
hi! curious if there is an alternate to the #installation download link (https://cronitor.io/dl/cronitor-stable-linux-amd64.tgz) where we can download a pinned version of the cronitor cli, eg `.../dl/cronitor-25.0-linux...`

**Comment by shaneharter** [comment]
Hi, sorry for the delay, you can now get these from Github Releases. For example:
https://github.com/cronitorio/cronitor-cli/releases/tag/28.0
