### ISSUE TITLE
Issue installing CronitorCLI in MacBook Air M1

### ISSUE THREAD

**Issue by timeowilliams** [cronitorio/cronitor-cli#8]
Hello, 

The steps listed in the [documentation ](https://cronitor.io/docs/using-cronitor-cli%23installation) to get the CronitorCLI up and running are as follows: 
1. curl -sOL https://cronitor.io/dl/cronitor-stable-darwin-amd64.zip
2. sudo unzip cronitor-stable-darwin-amd64.zip -d /usr/bin/

<img width="502" alt="Screen Shot 2021-08-02 at 4 26 27 PM" src="https://user-images.githubusercontent.com/19152894/127919546-20d78153-6b91-4a6a-9505-0d8881f19c26.png">

The first command successfully creates the zip file. However, the second command has an access error.

**Comment by jameszaghini** [comment]
I have the same problem macOS 11.4, Intel MBP

**Comment by timeowilliams** [comment]
> I have the same problem macOS 11.4, Intel MBP.
> 
> I installed to /usr/local/bin instead

Thanks @jameszaghini. That solved the issue for the time being.
