### ISSUE TITLE
cronitor-cli no longer working in Alpine Linux

### ISSUE THREAD

**Issue by FacetGraph** [cronitorio/cronitor-cli#9]
I build cronitor-cli into one of my docker images which uses alpine linux 3.13 and recently noticed the download URL changed, so I updated that, but then realized cronitor-cli no longer worked.

Commands I run in Dockerfile
```
 RUN curl -sOL https://cronitor.io/dl/linux_amd64.tar.gz                                                                                     
 RUN tar xvf linux_amd64.tar.gz -C /usr/bin/ 
```
Output from command
```
/web # /usr/bin/cronitor 
/bin/sh: /usr/bin/cronitor: not found
/web # ls -l /usr/bin/cronitor
-rwxr-xr-x    1 root     root      14678502 Oct  4 14:38 /usr/bin/cronitor
```

I realized the previous version I had been downloading from https://cronitor.io/dl/cronitor-stable-linux-amd64.tgz had been statically linked, and the new version in 28.2 is dynamically linked. I confirmed this by fetching the tar.gz Source Code and compiling it statically, which then worked inside alpine linux. I used this command,
```
go build -ldflags '-linkmode external -w -extldflags "-static"'
```
Is this something where you may go back to a statically linked binary or do you have a different recommendation?

**Comment by shaneharter** [comment]
Hi Matt, 

Thanks for reporting this. This is an unintended change and we will release a 28.3 build today that is statically linked. Please accept my apologies for the trouble. 

The backstory is that last week one of our vendors that provided build and CDN hosting for CronitorCLI shut down and we replaced this with a new pipeline. We do not currently use Alpine in our post-release verification, but I will fix that too going forward.

**Comment by shaneharter** [comment]
Hi Matt, 

I admit, across the various combinations of GOOS and GOARCH, this gave me a little more trouble than I expected it would. That said, I have built a 28.4 build that I can download and run in alpine:latest. Please give it a look and let me know if you have any issues. 

Best, 
Shane
